version: 2

updates:
  - package-ecosystem: "terraform"
    directory: "/dependabot-terraform/project-a"
    schedule:
      interval: "daily"

  - package-ecosystem: "terraform"
    directory: "/dependabot-terraform/project-b"
    schedule:
      interval: "daily"
