version: '3'
services:
  mqtt:
    image: eclipse-mosquitto

  hass:
    image: homeassistant/home-assistant
    ports:
    - "8123:8123"
    volumes:
      - ./config/hass:/config
    links:
    - mqtt
